version: "1"

secrets:
  - name: docker_username
    key: ecco/docker_username
    engine: native
    type: org
  - name: docker_password
    key: ecco/docker_password
    engine: native
    type: org

steps:
  - name: build and publish image to artifactory
    image: docker.target.com/vela-plugins/kaniko:v0.7.0-1
    ruleset:
      branch:
        - main
      event:
        - push
    secrets:
      - docker_username
      - docker_password
    parameters:
      registry: docker.target.com
      repo: docker.target.com/checkout/scheduled-scaler
      tags:
        - "b${BUILD_NUMBER}-${BUILD_COMMIT:0:8}"
