## DB
POSTGRES_ADDRESS = 'pgclx21201' 
POSTGRES_PORT = '5432'
POSTGRES_USERNAME = 'oph' 
POSTGRES_PASSWORD =''
POSTGRES_DBNAME = 'oph'
## TAP
CLOUD_URL='https://tapi-tagg.prod.platform.target.com'
CLOUD_APPLICATION = 'cartsv4'
CLOUD_CLUSTER = 'cartsv4-digital-npe'
CLOUD_USER = 'svgitecco'
CLOUD_PASSWORD = ""
CLOUD_ENVIRONMENT = 'dev'
CLOUD_APPLICATION_SECONDARY = 'checkouts'
CLOUD_CLUSTER_SECONDARY = 'checkouts-digital-npe'
### alerting
OAUTH_URL= 'https://oauth.iam.target.com/auth/oauth/v2/token'
OAUTH_USER_NAME= 'SVECOTOOLPRD'
OAUTH_CLIENT_ID= 'ec_automation_ropc'
OAUTH_PASSWORD= ''
OAUTH_CLIENT_SECRET= ''
ALERT_API_KEY='39a7e17803b8689675090ea37a0eda88f0b280cf'
ALERT_TOKEN=''
### OPH 
EXPECTED_OPH_FOR_20K=30
EXPECTED_OPH_FOR_35K=50
EXPECTED_OPH_FOR_50K=75
EXPECTED_OPH_FOR_70K=105
EXPECTED_OPH_FOR_100K=150
EXPECTED_OPH_FOR_150K=225
EXPECTED_OPH_FOR_200K=300
EXPECTED_OPH_FOR_250K=375
EXPECTED_OPH_FOR_300K=450
### scaling misc 
BATCH_SCALING_SIZE=4
SCALING_UP_THRESOLD=0.05
SCALING_DOWN_THRESOLD=-1.0
SCALING_MIN_CAPACITY=50
SCALING_CARTS_TO_CHECKOUT_RATIO=10

